### ISSUE TITLE
Setup Git to enforce unix line endings for setup-flex.sh

### ISSUE THREAD

**Issue by Stadler76** [brrritssocold/CoC-build-dependencies#1]
Had the following issue:
```bash
: not foundripts/setup-flex.sh: 15: /vagrant/scripts/setup-flex.sh:
--2018-03-05 13:29:55--  http://www-eu.apache.org/dist/flex/4.16.1%0D/binaries/apache-flex-sdk-4.16.1%0D-bin.tar.gz%0D
```

I've fixed that after opening up setup-flex.sh in Notepad++ and convert the line endings to UNIX line endings.

**Comment by brrritssocold** [comment]
Where did this happen?
Can you provide steps to reproduce the issue?

**Comment by Stadler76** [comment]
As per default Git converts line endings of text files to the corresponding line endings of the host system. Which is in my case CRLF or `\r\n` => in HTML: `%0D%0A` cuz I'm on Windows.
As solution may be: https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows
I'll try to fix this just now. Gimme a sec.
